/* The following code was generated by JFlex 1.7.0 tweaked for IntelliJ platform */

package org.example.language;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;

import static com.intellij.psi.TokenType.BAD_CHARACTER;
import static com.intellij.psi.TokenType.WHITE_SPACE;
import static org.example.language.CURLTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>_CURLLexer.flex</tt>
 */
public class _CURLLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   * Chosen bits are [9, 6, 6]
   * Total runtime size is 1568 bytes
   */
  public static int ZZ_CMAP(int ch) {
    return ZZ_CMAP_A[(ZZ_CMAP_Y[ZZ_CMAP_Z[ch>>12]|((ch>>6)&0x3f)]<<6)|(ch&0x3f)];
  }

  /* The ZZ_CMAP_Z table has 272 entries */
  static final char ZZ_CMAP_Z[] = zzUnpackCMap(
    "\1\0\1\100\1\200\u010d\100");

  /* The ZZ_CMAP_Y table has 192 entries */
  static final char ZZ_CMAP_Y[] = zzUnpackCMap(
    "\1\0\1\1\1\2\175\3\1\4\77\3");

  /* The ZZ_CMAP_A table has 320 entries */
  static final char ZZ_CMAP_A[] = zzUnpackCMap(
    "\11\0\1\3\4\2\22\0\1\3\1\25\1\31\1\26\1\0\2\26\1\27\3\0\1\26\1\25\1\33\1\25"+
    "\1\24\12\32\1\23\1\25\1\0\1\26\1\0\1\25\1\26\1\37\1\26\1\4\1\51\1\47\1\26"+
    "\1\42\1\45\1\56\2\26\1\7\1\26\1\55\1\53\1\52\1\26\1\6\1\54\1\50\1\5\2\26\1"+
    "\43\1\26\1\32\1\0\1\30\2\0\1\32\1\0\1\34\1\32\1\10\1\36\1\22\1\20\1\40\1\14"+
    "\1\21\2\32\1\13\1\32\1\35\1\46\1\16\1\44\1\12\1\17\1\15\1\11\3\32\1\41\1\32"+
    "\1\0\1\26\1\0\1\26\6\0\1\1\242\0\2\1\26\0");

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\2\4\1\12\2\2\0\4\1"+
    "\1\4\1\0\1\5\3\0\1\6\1\0\1\6\10\0"+
    "\4\1\7\0\1\7\4\0\1\10\1\0\1\10\1\1"+
    "\25\0\1\6\14\0\1\11\3\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292\0\u02c1"+
    "\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\u03db\0\u040a\0\u0439"+
    "\0\u0468\0\u01a7\0\57\0\u0497\0\u01d6\0\u04c6\0\57\0\u04f5"+
    "\0\u0524\0\u0553\0\u0582\0\u05b1\0\u05e0\0\u060f\0\u063e\0\u066d"+
    "\0\u069c\0\u06cb\0\u06fa\0\u0729\0\u0758\0\u0787\0\u07b6\0\u07e5"+
    "\0\u0814\0\u0843\0\u0872\0\u08a1\0\57\0\u08d0\0\u08ff\0\u092e"+
    "\0\u095d\0\57\0\u098c\0\353\0\u09bb\0\u09ea\0\u0a19\0\u0a48"+
    "\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33\0\u0b62\0\u0b91\0\u0bc0"+
    "\0\u0bef\0\u0c1e\0\u0c4d\0\u0c7c\0\u0cab\0\u0cda\0\u0d09\0\u0d38"+
    "\0\u0d67\0\u0d96\0\u0dc5\0\u0df4\0\u0e23\0\u0e52\0\u0e81\0\u0eb0"+
    "\0\u0edf\0\u0f0e\0\u0f3d\0\u0f6c\0\u0f9b\0\u0fca\0\u0ff9\0\u0f0e"+
    "\0\u1028\0\u1057\0\u1086";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\2\2\3\1\4\3\2\1\5\3\6\1\7\3\6"+
    "\1\10\2\6\1\2\1\11\2\2\1\12\1\2\1\13"+
    "\1\6\1\14\6\6\1\15\1\2\1\6\1\16\1\6"+
    "\1\2\1\17\1\20\1\21\1\22\3\2\61\0\2\3"+
    "\60\0\1\23\45\0\1\24\13\0\1\6\1\25\11\6"+
    "\7\0\1\6\1\0\6\6\2\0\1\6\1\0\1\6"+
    "\20\0\13\6\7\0\1\6\1\0\6\6\2\0\1\6"+
    "\1\0\1\6\20\0\5\6\1\26\5\6\7\0\1\6"+
    "\1\0\6\6\2\0\1\6\1\0\1\6\20\0\5\6"+
    "\1\27\3\6\1\30\1\6\7\0\1\6\1\0\6\6"+
    "\2\0\1\6\1\0\1\6\34\0\1\31\32\0\27\32"+
    "\1\33\1\34\26\32\30\35\1\36\1\33\25\35\11\0"+
    "\1\37\21\0\1\40\1\41\2\0\1\37\2\0\2\37"+
    "\1\0\2\37\57\0\1\42\56\0\1\43\15\0\1\44"+
    "\117\0\1\45\14\0\1\42\45\0\1\46\55\0\1\47"+
    "\12\0\1\50\125\0\1\51\11\0\2\6\1\52\10\6"+
    "\7\0\1\6\1\0\6\6\2\0\1\6\1\0\1\6"+
    "\20\0\5\6\1\53\5\6\7\0\1\6\1\0\6\6"+
    "\2\0\1\6\1\0\1\6\20\0\6\6\1\54\4\6"+
    "\7\0\1\6\1\0\6\6\2\0\1\6\1\0\1\6"+
    "\20\0\3\6\1\55\7\6\7\0\1\6\1\0\6\6"+
    "\2\0\1\6\1\0\1\6\10\0\1\31\2\0\54\31"+
    "\1\32\2\0\54\32\1\35\2\0\54\35\11\0\1\56"+
    "\1\57\1\0\1\60\17\0\1\61\3\0\1\62\5\0"+
    "\1\63\45\0\1\64\71\0\1\65\45\0\1\66\56\0"+
    "\1\67\26\0\1\70\123\0\1\42\52\0\1\71\15\0"+
    "\1\72\124\0\1\73\11\0\3\6\1\74\7\6\7\0"+
    "\1\6\1\0\6\6\2\0\1\6\1\0\1\6\20\0"+
    "\6\6\1\75\4\6\7\0\1\6\1\0\6\6\2\0"+
    "\1\6\1\0\1\6\20\0\13\6\1\76\6\0\1\6"+
    "\1\0\6\6\2\0\1\6\1\0\1\6\20\0\12\6"+
    "\1\54\7\0\1\6\1\0\6\6\2\0\1\6\1\0"+
    "\1\6\27\0\1\77\61\0\1\100\56\0\1\101\52\0"+
    "\1\102\62\0\1\103\45\0\1\104\106\0\1\105\66\0"+
    "\1\65\11\0\1\106\121\0\1\107\65\0\1\110\47\0"+
    "\1\111\17\0\7\6\1\54\3\6\1\76\6\0\1\6"+
    "\1\0\6\6\2\0\1\6\1\0\1\6\34\0\1\112"+
    "\54\0\1\113\100\0\1\114\46\0\1\115\40\0\1\116"+
    "\55\0\1\37\56\0\1\117\75\0\1\120\71\0\1\65"+
    "\57\0\1\106\61\0\1\121\7\0\1\42\76\0\1\122"+
    "\44\0\1\123\55\0\1\124\103\0\1\125\42\0\1\126"+
    "\52\0\1\127\51\0\1\130\122\0\1\131\5\0\23\132"+
    "\3\0\25\132\33\0\1\133\45\0\1\134\56\0\1\135"+
    "\71\0\1\136\32\0\1\103\62\0\1\137\115\0\1\65"+
    "\6\0\17\140\1\132\1\140\1\132\1\140\3\0\25\140"+
    "\34\0\1\141\41\0\1\103\51\0\1\37\102\0\1\37"+
    "\34\0\1\37\102\0\1\142\40\0\1\143\71\0\1\103"+
    "\21\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4277];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\20\1\2\0\5\1\1\0\1\11\3\0"+
    "\1\11\1\0\1\1\10\0\4\1\7\0\1\11\4\0"+
    "\1\11\1\0\2\1\25\0\1\1\14\0\1\1\3\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  public _CURLLexer() {
    this((java.io.Reader)null);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _CURLLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    int size = 0;
    for (int i = 0, length = packed.length(); i < length; i += 2) {
      size += packed.charAt(i);
    }
    char[] map = new char[size];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < packed.length()) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + ZZ_CMAP(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return BASIC_STRING;
            } 
            // fall through
          case 10: break;
          case 2: 
            { return BAD_CHARACTER;
            } 
            // fall through
          case 11: break;
          case 3: 
            { return WHITE_SPACE;
            } 
            // fall through
          case 12: break;
          case 4: 
            { return COMMENT;
            } 
            // fall through
          case 13: break;
          case 5: 
            { return QUOTED_STRING;
            } 
            // fall through
          case 14: break;
          case 6: 
            { return OPTION;
            } 
            // fall through
          case 15: break;
          case 7: 
            { return METHOD;
            } 
            // fall through
          case 16: break;
          case 8: 
            { return CURL;
            } 
            // fall through
          case 17: break;
          case 9: 
            { return URL;
            } 
            // fall through
          case 18: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
